In [1]:
import pandas as pd
from pathlib import Path

In [2]:
orders = pd.read_csv("orders.csv")
tracking = pd.read_csv("carrier_tracking.csv")

In [4]:
orders

,order_id,buyer_handle,seller_handle,item,price_usd,dispute_reason,dispute_filed_date
0,D1001,alex_p90,retro_finds,Vintage Camera,145,Never received,2025-01-07
1,D1002,dana_m,boutique_threads,Leather Jacket,210,Wrong item received,2025-01-08
2,D1003,quick_flip99,north_collectibles,Signed Baseball,89,Never received,2025-01-08
3,D1004,helen_ok,stagegear_co,Guitar Pedal,60,Damaged on arrival,2025-01-09
4,D1005,reggie_t,north_collectibles,Comic Book Lot,150,Never received,2025-01-12
5,D1006,priya_s,gearhead_supply,Bike Helmet,75,Not as described,2025-01-13
6,D1007,derek_w,boutique_threads,Sneakers,220,Wrong size shipped,2025-01-14
7,D1008,quick_flip99,audio_attic,Turntable,180,Never received,2025-01-19
8,D1009,monica_lee,retro_finds,Record Player Needle,25,Never received,2025-01-20
9,D1010,sam_k,gearhead_supply,Weight Plates,95,Never received,2025-01-21
10,D1011,nina_v,north_collectibles,Vinyl Record,40,Arrived broken,2025-01-22
11,D1012,theo_b,audio_attic,Headphones,130,Seller unresponsive - never shipped,2025-01-25
12,D1013,quick_flip99,stagegear_co,Microphone,99,Never received,2025-02-02
13,D1014,carla_m,boutique_threads,Handbag,175,Suspected counterfeit,2025-02-03
14,D1015,jorge_l,retro_finds,Polaroid Camera,85,Never received,2025-02-05
15,D1016,fatima_r,gearhead_supply,Resistance Bands,20,Wrong color,2025-02-06
16,D1017,quick_flip99,retro_finds,Cassette Deck,110,Never received,2025-02-14
17,D1018,owen_d,boutique_threads,Denim Jacket,95,Never received,2025-02-16
18,D1019,liang_c,audio_attic,Guitar Amp,250,Arrived - does not power on,2025-02-17
19,D1020,priya_s,stagegear_co,Effects Pedal,70,Wrong item shipped,2025-02-18

In [5]:
tracking

,order_id,carrier,signature_required,signed_by,delivery_status,last_scan_date,last_scan_location,delivered_date,delivery_notes
0,D1001,ParcelEx,No,NaN,Delivered,2025-01-05,local depot,2025-01-05,left at front door
1,D1002,ParcelEx,Yes,D.MERCADO,Delivered,2025-01-07,NaN,2025-01-07,signed at front desk
2,D1003,SwiftShip,No,NaN,Delivered,2025-01-07,local depot,2025-01-07,left at door no signature
3,D1004,ParcelEx,No,NaN,Delivered,2025-01-08,local depot,2025-01-08,left at door
4,D1005,SwiftShip,No,NaN,In Transit,2025-01-10,regional hub - 300mi from delivery address,NaN,not yet delivered - tracking stalled
5,D1006,ParcelEx,No,NaN,Delivered,2025-01-11,local depot,2025-01-11,left at door
6,D1007,ParcelEx,Yes,D.W.,Delivered,2025-01-13,NaN,2025-01-13,signed by recipient
7,D1008,SwiftShip,No,NaN,Delivered,2025-01-18,local depot,2025-01-18,left at door no signature
8,D1009,ParcelEx,No,NaN,Delivered,2025-01-17,local depot,2025-01-17,left at door
9,D1010,ParcelEx,Yes,S.KAPOOR,Delivered,2025-01-19,NaN,2025-01-19,signed by recipient
10,D1011,SwiftShip,No,NaN,Delivered,2025-01-21,local depot,2025-01-21,left at door
11,D1012,ParcelEx,No,NaN,Label Created,2025-01-13,origin facility,NaN,never picked up by carrier - no scans after la...
12,D1013,SwiftShip,No,NaN,Delivered,2025-02-01,local depot,2025-02-01,left at door no signature
13,D1014,ParcelEx,Yes,C.M.,Delivered,2025-02-01,NaN,2025-02-01,signed by recipient
14,D1015,SwiftShip,No,NaN,Delivered,2025-02-03,local depot,2025-02-03,left at door no signature - delivered to stree...
15,D1016,ParcelEx,No,NaN,Delivered,2025-02-05,local depot,2025-02-05,left at door
16,D1017,SwiftShip,No,NaN,Delivered,2025-02-13,local depot,2025-02-13,left at door no signature
17,D1018,ParcelEx,Yes,O.DAVIS,Delivered,2025-02-10,NaN,2025-02-10,signed by recipient
18,D1019,ParcelEx,Yes,L.C.,Delivered,2025-02-15,NaN,2025-02-15,signed by recipient
19,D1020,ParcelEx,No,NaN,Delivered,2025-02-17,local depot,2025-02-17,left at door

In [10]:
orders.shape

(20, 7)

In [11]:
tracking.shape

(20, 9)

In [14]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            20 non-null     str
 1   buyer_handle        20 non-null     str
 2   seller_handle       20 non-null     str
 3   item                20 non-null     str
 4   price_usd           20 non-null     int64
 5   dispute_reason      20 non-null     str
 6   dispute_filed_date  20 non-null     str
dtypes: int64(1), str(6)
memory usage: 1.2 KB

In [15]:
tracking.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            20 non-null     str
 1   carrier             20 non-null     str
 2   signature_required  20 non-null     str
 3   signed_by           6 non-null      str
 4   delivery_status     20 non-null     str
 5   last_scan_date      20 non-null     str
 6   last_scan_location  14 non-null     str
 7   delivered_date      18 non-null     str
 8   delivery_notes      20 non-null     str
dtypes: str(9)
memory usage: 1.5 KB

In [20]:
print("Missing values in orders:")
display(orders.isnull().sum())

Missing values in orders:

order_id              0
buyer_handle          0
seller_handle         0
item                  0
price_usd             0
dispute_reason        0
dispute_filed_date    0
dtype: int64

In [21]:
print("Missing values in tracking:")
display(tracking.isnull().sum())

Missing values in tracking:

order_id               0
carrier                0
signature_required     0
signed_by             14
delivery_status        0
last_scan_date         0
last_scan_location     6
delivered_date         2
delivery_notes         0
dtype: int64

In [22]:
print("Duplicate order IDs in orders:",
      orders["order_id"].duplicated().sum())

Duplicate order IDs in orders: 0

In [23]:
print("Duplicate order IDs in tracking:",
      tracking["order_id"].duplicated().sum())

Duplicate order IDs in tracking: 0

In [24]:
tracking_ids = set(tracking["order_id"])
order_ids = set(orders["order_id"])

print("Orders without tracking:",
      order_ids - tracking_ids)

print("Tracking records without orders:",
      tracking_ids - order_ids)

Orders without tracking: set()
Tracking records without orders: set()

In [ ]:
merged = orders.merge(tracking,on="order_id",how="left",indicator=True,validate="one_to_one")
print(merged["_merge"].value_counts())
display(merged.head())

_merge
both          20
left_only      0
right_only     0
Name: count, dtype: int64

,order_id,buyer_handle,seller_handle,item,price_usd,dispute_reason,dispute_filed_date,carrier,signature_required,signed_by,delivery_status,last_scan_date,last_scan_location,delivered_date,delivery_notes,_merge
0,D1001,alex_p90,retro_finds,Vintage Camera,145,Never received,2025-01-07,ParcelEx,No,NaN,Delivered,2025-01-05,local depot,2025-01-05,left at front door,both
1,D1002,dana_m,boutique_threads,Leather Jacket,210,Wrong item received,2025-01-08,ParcelEx,Yes,D.MERCADO,Delivered,2025-01-07,NaN,2025-01-07,signed at front desk,both
2,D1003,quick_flip99,north_collectibles,Signed Baseball,89,Never received,2025-01-08,SwiftShip,No,NaN,Delivered,2025-01-07,local depot,2025-01-07,left at door no signature,both
3,D1004,helen_ok,stagegear_co,Guitar Pedal,60,Damaged on arrival,2025-01-09,ParcelEx,No,NaN,Delivered,2025-01-08,local depot,2025-01-08,left at door,both
4,D1005,reggie_t,north_collectibles,Comic Book Lot,150,Never received,2025-01-12,SwiftShip,No,NaN,In Transit,2025-01-10,regional hub - 300mi from delivery address,NaN,not yet delivered - tracking stalled,both

# Support chat

In [ ]:
chat_text = Path("support_chat.txt").read_text(encoding="utf-8")
print(chat_text[:3000])

In [27]:
import re

sections = re.split( r"===\s*(D\d+)\s*===",chat_text)

print("Number of dispute sections:", (len(sections) - 1) // 2)

print("\nFirst dispute ID:", sections[1])
print("\nFirst dispute conversation:")
print(sections[2].strip())

Number of dispute sections: 20

First dispute ID: D1001

First dispute conversation:
[2025-01-05] Buyer: just got the camera, looks great! does it come with a case?
[2025-01-06] Seller: glad it arrived! no case included, sorry about that
[2025-01-07] Buyer: wait, actually I never received this order, I need a refund

In [28]:
message_pattern = (
    r"\[(\d{4}-\d{2}-\d{2})\]\s*"
    r"(Buyer|Seller):\s*(.*)"
)

first_chat = sections[2].strip()

messages = re.findall(message_pattern, first_chat)

for date, speaker, message in messages:
    print({
        "date": date,
        "speaker": speaker,
        "message": message
    })

{'date': '2025-01-05', 'speaker': 'Buyer', 'message': 'just got the camera, looks great! does it come with a case?'}
{'date': '2025-01-06', 'speaker': 'Seller', 'message': 'glad it arrived! no case included, sorry about that'}
{'date': '2025-01-07', 'speaker': 'Buyer', 'message': 'wait, actually I never received this order, I need a refund'}

# Combine the three data sources

In [ ]:
# Check how the data connects
print("Orders columns:")
print(orders.columns.tolist())

print("\nTracking columns:")
print(tracking.columns.tolist())

print("\nFirst parsed dispute IDs:")
print(sections[1:10:2])

Orders columns:
['order_id', 'buyer_handle', 'seller_handle', 'item', 'price_usd', 'dispute_reason', 'dispute_filed_date']

Tracking columns:
['order_id', 'carrier', 'signature_required', 'signed_by', 'delivery_status', 'last_scan_date', 'last_scan_location', 'delivered_date', 'delivery_notes']

First parsed dispute IDs:
['D1001', 'D1002', 'D1003', 'D1004', 'D1005']

In [ ]:
# parsed messages into a DataFrame
chat_records = []

for i in range(1, len(sections), 2):
    dispute_id = sections[i].strip()
    conversation = sections[i + 1].strip()

    messages = re.findall(
        r"\[(\d{4}-\d{2}-\d{2})\]\s*"
        r"(Buyer|Seller):\s*(.*)",
        conversation
    )

    for date, speaker, message in messages:
        chat_records.append({
            "dispute_id": dispute_id,
            "date": date,
            "speaker": speaker,
            "message": message
        })

chat_df = pd.DataFrame(chat_records)

display(chat_df.head(10))
print("Total messages:", len(chat_df))
print("Total disputes:", chat_df["dispute_id"].nunique())

,dispute_id,date,speaker,message
0,D1001,2025-01-05,Buyer,"just got the camera, looks great! does it come..."
1,D1001,2025-01-06,Seller,"glad it arrived! no case included, sorry about..."
2,D1001,2025-01-07,Buyer,"wait, actually I never received this order, I ..."
3,D1002,2025-01-08,Buyer,"this is a grey jacket, I ordered the black one"
4,D1002,2025-01-08,Seller,"oh no, I think I mixed up your order with anot..."
5,D1003,2025-01-08,Buyer,"never got this, need a refund"
6,D1004,2025-01-09,Buyer,"pedal case arrived cracked, attaching a photo"
7,D1004,2025-01-09,Seller,so sorry - our listing says DOA damage is cove...
8,D1005,2025-01-12,Buyer,it's been over a week and tracking hasn't move...
9,D1005,2025-01-12,Seller,let me check with the carrier... yeah it looks...

Total messages: 41
Total disputes: 20

In [ ]:
# one conversation summary per dispute
chat_summary = (
    chat_df.sort_values("date")
    .groupby("dispute_id")
    .apply(
        lambda group: "\n".join(
            f"[{row.date}] {row.speaker}: {row.message}"
            for row in group.itertuples()
        )
    )
    .reset_index(name="conversation")
)

display(chat_summary.head())
#chat_summary

  dispute_id                                       conversation
0      D1001  [2025-01-05] Buyer: just got the camera, looks...
1      D1002  [2025-01-08] Buyer: this is a grey jacket, I o...
2      D1003  [2025-01-08] Buyer: never got this, need a refund
3      D1004  [2025-01-09] Buyer: pedal case arrived cracked...
4      D1005  [2025-01-12] Buyer: it's been over a week and ...

In [39]:
# Join the data
evidence = orders.merge(
    tracking,
    on="order_id",
    how="left",
    validate="one_to_one",
    indicator=True
)

print("Evidence shape:", evidence.shape)
print("\nTracking match status:")
print(evidence["_merge"].value_counts())

display(evidence.head()) 
# combines the two datasets using their shared order_id.

Evidence shape: (20, 16)

Tracking match status:
_merge
both          20
left_only      0
right_only     0
Name: count, dtype: int64

,order_id,buyer_handle,seller_handle,item,price_usd,dispute_reason,dispute_filed_date,carrier,signature_required,signed_by,delivery_status,last_scan_date,last_scan_location,delivered_date,delivery_notes,_merge
0,D1001,alex_p90,retro_finds,Vintage Camera,145,Never received,2025-01-07,ParcelEx,No,NaN,Delivered,2025-01-05,local depot,2025-01-05,left at front door,both
1,D1002,dana_m,boutique_threads,Leather Jacket,210,Wrong item received,2025-01-08,ParcelEx,Yes,D.MERCADO,Delivered,2025-01-07,NaN,2025-01-07,signed at front desk,both
2,D1003,quick_flip99,north_collectibles,Signed Baseball,89,Never received,2025-01-08,SwiftShip,No,NaN,Delivered,2025-01-07,local depot,2025-01-07,left at door no signature,both
3,D1004,helen_ok,stagegear_co,Guitar Pedal,60,Damaged on arrival,2025-01-09,ParcelEx,No,NaN,Delivered,2025-01-08,local depot,2025-01-08,left at door,both
4,D1005,reggie_t,north_collectibles,Comic Book Lot,150,Never received,2025-01-12,SwiftShip,No,NaN,In Transit,2025-01-10,regional hub - 300mi from delivery address,NaN,not yet delivered - tracking stalled,both

In [40]:
print("Order IDs:")
print(orders["order_id"].tolist())

print("\nDispute IDs:")
print(chat_summary["dispute_id"].tolist())

Order IDs:
['D1001', 'D1002', 'D1003', 'D1004', 'D1005', 'D1006', 'D1007', 'D1008', 'D1009', 'D1010', 'D1011', 'D1012', 'D1013', 'D1014', 'D1015', 'D1016', 'D1017', 'D1018', 'D1019', 'D1020']

Dispute IDs:
['D1001', 'D1002', 'D1003', 'D1004', 'D1005', 'D1006', 'D1007', 'D1008', 'D1009', 'D1010', 'D1011', 'D1012', 'D1013', 'D1014', 'D1015', 'D1016', 'D1017', 'D1018', 'D1019', 'D1020']

# complete evidence table

In [41]:
# Merge orders with tracking
evidence = orders.merge(
    tracking,
    on="order_id",
    how="left",
    validate="one_to_one"
)

# Merge the support conversations
evidence = evidence.merge(
    chat_summary,
    left_on="order_id",
    right_on="dispute_id",
    how="left",
    validate="one_to_one"
)

# Remove the redundant ID column
evidence = evidence.drop(columns=["dispute_id"])

print("Total disputes:", len(evidence))
print("Missing tracking records:", evidence["delivery_status"].isna().sum())
print("Missing conversations:", evidence["conversation"].isna().sum())

display(evidence.head())

Total disputes: 20
Missing tracking records: 0
Missing conversations: 0

,order_id,buyer_handle,seller_handle,item,price_usd,dispute_reason,dispute_filed_date,carrier,signature_required,signed_by,delivery_status,last_scan_date,last_scan_location,delivered_date,delivery_notes,conversation
0,D1001,alex_p90,retro_finds,Vintage Camera,145,Never received,2025-01-07,ParcelEx,No,NaN,Delivered,2025-01-05,local depot,2025-01-05,left at front door,"[2025-01-05] Buyer: just got the camera, looks..."
1,D1002,dana_m,boutique_threads,Leather Jacket,210,Wrong item received,2025-01-08,ParcelEx,Yes,D.MERCADO,Delivered,2025-01-07,NaN,2025-01-07,signed at front desk,"[2025-01-08] Buyer: this is a grey jacket, I o..."
2,D1003,quick_flip99,north_collectibles,Signed Baseball,89,Never received,2025-01-08,SwiftShip,No,NaN,Delivered,2025-01-07,local depot,2025-01-07,left at door no signature,"[2025-01-08] Buyer: never got this, need a refund"
3,D1004,helen_ok,stagegear_co,Guitar Pedal,60,Damaged on arrival,2025-01-09,ParcelEx,No,NaN,Delivered,2025-01-08,local depot,2025-01-08,left at door,[2025-01-09] Buyer: pedal case arrived cracked...
4,D1005,reggie_t,north_collectibles,Comic Book Lot,150,Never received,2025-01-12,SwiftShip,No,NaN,In Transit,2025-01-10,regional hub - 300mi from delivery address,NaN,not yet delivered - tracking stalled,[2025-01-12] Buyer: it's been over a week and ...

In [42]:
# Check for duplicate dispute/order IDs
print("Duplicate IDs:", evidence["order_id"].duplicated().sum())

# Check that all expected IDs are present
print("Missing IDs:", set(orders["order_id"]) - set(evidence["order_id"]))

# Inspect the key evidence fields
display(
    evidence[
        [
            "order_id",
            "dispute_reason",
            "delivery_status",
            "signed_by",
            "delivery_notes",
            "conversation"
        ]
    ].head(10)
)

Duplicate IDs: 0
Missing IDs: set()

,order_id,dispute_reason,delivery_status,signed_by,delivery_notes,conversation
0,D1001,Never received,Delivered,NaN,left at front door,"[2025-01-05] Buyer: just got the camera, looks..."
1,D1002,Wrong item received,Delivered,D.MERCADO,signed at front desk,"[2025-01-08] Buyer: this is a grey jacket, I o..."
2,D1003,Never received,Delivered,NaN,left at door no signature,"[2025-01-08] Buyer: never got this, need a refund"
3,D1004,Damaged on arrival,Delivered,NaN,left at door,[2025-01-09] Buyer: pedal case arrived cracked...
4,D1005,Never received,In Transit,NaN,not yet delivered - tracking stalled,[2025-01-12] Buyer: it's been over a week and ...
5,D1006,Not as described,Delivered,NaN,left at door,[2025-01-13] Seller: it was one small scuff on...
6,D1007,Wrong size shipped,Delivered,D.W.,signed by recipient,"[2025-01-14] Buyer: got these, but they're a s..."
7,D1008,Never received,Delivered,NaN,left at door no signature,"[2025-01-19] Buyer: never received this, pleas..."
8,D1009,Never received,Delivered,NaN,left at door,[2025-01-18] Buyer: hey it's been a day since ...
9,D1010,Never received,Delivered,S.KAPOOR,signed by recipient,"[2025-01-21] Buyer: I never got this, someone ..."

In [43]:
print("Dispute reasons:")
display(evidence["dispute_reason"].value_counts())

print("\nDelivery statuses:")
display(evidence["delivery_status"].value_counts())

print("\nDelivery notes:")
display(evidence["delivery_notes"].value_counts())

Dispute reasons:

dispute_reason
Never received                         10
Wrong item received                     1
Damaged on arrival                      1
Not as described                        1
Wrong size shipped                      1
Arrived broken                          1
Seller unresponsive - never shipped     1
Suspected counterfeit                   1
Wrong color                             1
Arrived - does not power on             1
Wrong item shipped                      1
Name: count, dtype: int64

Delivery statuses:

delivery_status
Delivered        18
In Transit        1
Label Created     1
Name: count, dtype: int64

Delivery notes:

delivery_notes
left at door                                                                    6
signed by recipient                                                             5
left at door no signature                                                       4
left at front door                                                              1
signed at front desk                                                            1
not yet delivered - tracking stalled                                            1
never picked up by carrier - no scans after label creation                      1
left at door no signature - delivered to street address on file at ship time    1
Name: count, dtype: int64

# Decision Engine

In [55]:

def clean_text(value):
    """Convert missing values to empty strings and normalize text."""
    if pd.isna(value):
        return ""
    return str(value).lower().strip()


def has_any(text, phrases):
    return any(phrase in text for phrase in phrases)


def make_decision(row):
    # -----------------------------
    # 1. Read and normalize evidence
    # -----------------------------
    reason = clean_text(row.get("dispute_reason", ""))
    status = clean_text(row.get("delivery_status", ""))
    notes = clean_text(row.get("delivery_notes", ""))
    signed_by = clean_text(row.get("signed_by", ""))
    chat = clean_text(row.get("conversation", ""))

    evidence = (
        f"Reason: {reason}; Status: {status}; "
        f"Signed by: {signed_by or 'not recorded'}; "
        f"Tracking notes: {notes}; Conversation: {chat}"
    )

    def result(verdict, confidence, explanation, rule):
        return {
            "verdict": verdict,
            "confidence": confidence,
            "reason": explanation,
            "evidence": evidence,
            "rule_applied": rule
        }

    # -----------------------------
    # 2. Identify the dispute type
    # -----------------------------
    non_receipt = has_any(reason, [
        "never received",
        "not received",
        "item not received",
        "never arrived",
        "did not arrive"
    ])

    damage_issue = has_any(reason, [
        "damaged",
        "damage",
        "broken",
        "does not power on",
        "doesn't power on",
        "not working",
        "faulty",
        "defective"
    ])

    # -----------------------------
    # RULE 1: Non-delivery
    # -----------------------------
    non_delivery_status = has_any(status, [
        "in transit",
        "label created",
        "not picked up",
        "lost",
        "returned to sender",
        "exception"
    ])

    non_delivery_notes = has_any(notes, [
        "never picked up",
        "not yet delivered",
        "lost in transit",
        "never collected",
        "not handed to carrier"
    ])

    wrong_address_delivery = (
        "delivered to wrong address" in notes
        or "delivered to a different address" in notes
    )

    if (
        non_delivery_status
        or non_delivery_notes
        or wrong_address_delivery
    ):
        return result(
            "refund",
            "high",
            "Tracking evidence indicates the item was not delivered "
            "to the buyer as expected.",
            "Rule 1 — Non-delivery"
        )

    # -----------------------------
    # RULE 2: Seller acknowledges error
    # -----------------------------
    seller_error_phrases = [
        "mixed up your order",
        "mixed up the order",
        "sent the wrong item",
        "shipped the wrong item",
        "grabbed the wrong one",
        "wrong item",
        "mislabeled the box",
        "mislabelled the box",
        "wrong size",
        "incorrect size",
        "listing was incorrect",
        "listing was wrong",
        "my mistake",
        "that's on me",
        "that is on me"
    ]

    seller_admits_error = has_any(chat, seller_error_phrases)

    # A specific seller admission of a listing/fulfillment error
    # takes precedence over later generic delivery evidence.
    if seller_admits_error:
        return result(
            "refund",
            "high",
            "The seller acknowledges a listing or fulfillment error.",
            "Rule 2 — Seller acknowledges error"
        )

    # -----------------------------
    # Seller confirms damage coverage
    # -----------------------------
    damage_coverage_phrases = [
        "damage is covered",
        "doa damage is covered",
        "covered under our policy",
        "covered by our policy"
    ]

    refund_commitment_phrases = [
        "refunding you",
        "refunding now",
        "i'll refund",
        "i will refund",
        "i'll issue a refund",
        "i will issue a refund",
        "issuing a refund",
        "refund you"
    ]

    if (
        damage_issue
        and has_any(chat, damage_coverage_phrases)
        and has_any(chat, refund_commitment_phrases)
    ):
        return result(
            "refund",
            "high",
            "The seller confirms that the reported damage is covered "
            "and explicitly commits to a refund.",
            "Seller-confirmed damage coverage"
        )

    # A seller explicitly promising a refund for a reported fault
    if (
        damage_issue
        and has_any(chat, refund_commitment_phrases)
        and has_any(chat, [
            "that's a real fault",
            "that is a real fault",
            "packaging was too thin",
            "packaging was inadequate",
            "item was faulty",
            "item is faulty",
            "arrived broken",
            "doesn't work",
            "does not work"
        ])
    ):
        return result(
            "refund",
            "high",
            "The seller acknowledges the reported fault and explicitly "
            "promises a refund.",
            "Seller-confirmed fault and refund"
        )

    # -----------------------------
    # RULE 3 / 4: Non-receipt claims
    # -----------------------------
    buyer_receipt_phrases = [
        "i received it",
        "i got it",
        "it arrived",
        "package arrived",
        "item arrived",
        "got the package",
        "got the item",
        "love the jacket",
        "thanks, got it"
    ]

    buyer_denies_receipt_phrases = [
        "never got this",
        "never received",
        "i didn't receive",
        "i did not receive",
        "i never got",
        "someone else must have signed",
        "someone else signed",
        "not my signature",
        "i wasn't home",
        "i was not home"
    ]

    receipt_retraction_phrases = [
        "maybe it was a different package",
        "might have been a different package",
        "packages were mixed",
        "not sure that was this item",
        "i may have been mistaken"
    ]

    buyer_acknowledged_receipt = has_any(
        chat, buyer_receipt_phrases
    )

    buyer_denies_receipt = has_any(
        chat, buyer_denies_receipt_phrases
    )

    receipt_retracted = has_any(
        chat, receipt_retraction_phrases
    )

    signed_delivery = (
        status == "delivered"
        and signed_by not in ["", "nan", "none", "not recorded", "unknown"]
    )

    delivered = "delivered" in status

    # A buyer disputes who signed: evidence conflicts.
    if non_receipt and has_any(chat, [
        "someone else must have signed",
        "someone else signed",
        "not my signature"
    ]):
        return result(
            "escalate",
            "medium",
            "Tracking records a signature, but the buyer disputes "
            "who signed for the delivery.",
            "Rule 4 — Conflicting evidence"
        )

    # Receipt acknowledged, then contradicted or retracted.
    if (
        non_receipt
        and buyer_acknowledged_receipt
        and (buyer_denies_receipt or receipt_retracted)
    ):
        return result(
            "escalate",
            "low",
            "Receipt evidence is contradicted or retracted in the "
            "conversation.",
            "Rule 4 — Conflicting evidence"
        )

    # Credible receipt evidence conflicts with a non-receipt claim.
    if non_receipt and buyer_acknowledged_receipt:
        return result(
            "deny",
            "medium",
            "The buyer's own messages indicate receipt, which conflicts "
            "with the non-receipt claim.",
            "Rule 3 — Confirmed receipt"
        )

    # Signed delivery alone is not enough if the buyer disputes it.
    if non_receipt and signed_delivery:
        return result(
            "escalate",
            "medium",
            "Tracking records a signature, but the available evidence "
            "does not establish that the buyer received the item.",
            "Rule 4 — Conflicting or insufficient evidence"
        )

    # Delivered but no reliable receipt confirmation.
    if non_receipt and delivered:
        return result(
            "escalate",
            "low",
            "Tracking says delivered, but there is no reliable evidence "
            "that the buyer received the item.",
            "Rule 4 — Insufficient evidence"
        )

    # Non-receipt with unclear tracking.
    if non_receipt:
        return result(
            "escalate",
            "low",
            "The available tracking and conversation evidence is "
            "insufficient to determine whether delivery occurred.",
            "Rule 4 — Insufficient evidence"
        )

    # -----------------------------
    # RULE 5: Already resolved
    # -----------------------------
    buyer_acceptance_phrases = [
        "partial refund is fine",
        "i accept the partial refund",
        "i accept the refund",
        "that works for me",
        "exchange is fine",
        "i agree to the exchange",
        "i accept the exchange"
    ]

    seller_resolution_phrases = [
        "partial refund",
        "offer an exchange",
        "offer a refund",
        "i'll refund",
        "i will refund",
        "refunding now",
        "send a replacement",
        "replace the item"
    ]

    if (
        has_any(chat, buyer_acceptance_phrases)
        and has_any(chat, seller_resolution_phrases)
    ):
        return result(
            "deny",
            "medium",
            "The conversation indicates that both parties accepted "
            "a resolution to the issue.",
            "Rule 5 — Issue already resolved"
        )

    # -----------------------------
    # RULE 4: Default to escalation
    # -----------------------------
    return result(
        "escalate",
        "low",
        "Evidence is insufficient or conflicting, so the case requires "
        "manual review.",
        "Rule 4 — Insufficient or conflicting evidence"
    )


# --------------------------------
# Apply decisions to all disputes
# --------------------------------
decisions = evidence.apply(make_decision, axis=1, result_type="expand")

results = pd.concat(
    [
        evidence[
            [
                "order_id",
                "buyer_handle",
                "seller_handle",
                "dispute_reason"
            ]
        ].reset_index(drop=True),
        decisions.reset_index(drop=True)
    ],
    axis=1
)

# --------------------------------
# Add history review flags
# --------------------------------
buyer_counts = evidence["buyer_handle"].value_counts()
seller_counts = evidence["seller_handle"].value_counts()

results["repeat_buyer_flag"] = (
    results["buyer_handle"].map(buyer_counts).gt(1)
)

results["repeat_seller_flag"] = (
    results["seller_handle"].map(seller_counts).gt(1)
)

results["history_review"] = (
    results["repeat_buyer_flag"]
    | results["repeat_seller_flag"]
)

# --------------------------------
# Review and export
# --------------------------------
print("Verdict counts:")
print(results["verdict"].value_counts())

print("\nDecision preview:")
display(results)

results.to_csv("reloop_decisions.csv", index=False)

print("\nSaved: reloop_decisions.csv")

Verdict counts:
verdict
escalate    11
refund       8
deny         1
Name: count, dtype: int64

Decision preview:

,order_id,buyer_handle,seller_handle,dispute_reason,verdict,confidence,reason,evidence,rule_applied,repeat_buyer_flag,repeat_seller_flag,history_review
0,D1001,alex_p90,retro_finds,Never received,escalate,low,Receipt evidence is contradicted or retracted ...,Reason: never received; Status: delivered; Sig...,Rule 4 — Conflicting evidence,False,True,True
1,D1002,dana_m,boutique_threads,Wrong item received,refund,high,The seller acknowledges a listing or fulfillme...,Reason: wrong item received; Status: delivered...,Rule 2 — Seller acknowledges error,False,True,True
2,D1003,quick_flip99,north_collectibles,Never received,escalate,low,"Tracking says delivered, but there is no relia...",Reason: never received; Status: delivered; Sig...,Rule 4 — Insufficient evidence,True,True,True
3,D1004,helen_ok,stagegear_co,Damaged on arrival,refund,high,The seller confirms that the reported damage i...,Reason: damaged on arrival; Status: delivered;...,Seller-confirmed damage coverage,False,True,True
4,D1005,reggie_t,north_collectibles,Never received,refund,high,Tracking evidence indicates the item was not d...,Reason: never received; Status: in transit; Si...,Rule 1 — Non-delivery,False,True,True
5,D1006,priya_s,gearhead_supply,Not as described,escalate,low,"Evidence is insufficient or conflicting, so th...",Reason: not as described; Status: delivered; S...,Rule 4 — Insufficient or conflicting evidence,True,True,True
6,D1007,derek_w,boutique_threads,Wrong size shipped,refund,high,The seller acknowledges a listing or fulfillme...,Reason: wrong size shipped; Status: delivered;...,Rule 2 — Seller acknowledges error,False,True,True
7,D1008,quick_flip99,audio_attic,Never received,escalate,low,"Tracking says delivered, but there is no relia...",Reason: never received; Status: delivered; Sig...,Rule 4 — Insufficient evidence,True,True,True
8,D1009,monica_lee,retro_finds,Never received,escalate,low,"Tracking says delivered, but there is no relia...",Reason: never received; Status: delivered; Sig...,Rule 4 — Insufficient evidence,False,True,True
9,D1010,sam_k,gearhead_supply,Never received,escalate,medium,"Tracking records a signature, but the buyer di...",Reason: never received; Status: delivered; Sig...,Rule 4 — Conflicting evidence,False,True,True
10,D1011,nina_v,north_collectibles,Arrived broken,refund,high,The seller acknowledges the reported fault and...,Reason: arrived broken; Status: delivered; Sig...,Seller-confirmed fault and refund,False,True,True
11,D1012,theo_b,audio_attic,Seller unresponsive - never shipped,refund,high,Tracking evidence indicates the item was not d...,Reason: seller unresponsive - never shipped; S...,Rule 1 — Non-delivery,False,True,True
12,D1013,quick_flip99,stagegear_co,Never received,escalate,low,"Tracking says delivered, but there is no relia...",Reason: never received; Status: delivered; Sig...,Rule 4 — Insufficient evidence,True,True,True
13,D1014,carla_m,boutique_threads,Suspected counterfeit,escalate,low,"Evidence is insufficient or conflicting, so th...",Reason: suspected counterfeit; Status: deliver...,Rule 4 — Insufficient or conflicting evidence,False,True,True
14,D1015,jorge_l,retro_finds,Never received,escalate,low,"Tracking says delivered, but there is no relia...",Reason: never received; Status: delivered; Sig...,Rule 4 — Insufficient evidence,False,True,True
15,D1016,fatima_r,gearhead_supply,Wrong color,deny,medium,The conversation indicates that both parties a...,Reason: wrong color; Status: delivered; Signed...,Rule 5 — Issue already resolved,False,True,True
16,D1017,quick_flip99,retro_finds,Never received,escalate,low,"Tracking says delivered, but there is no relia...",Reason: never received; Status: delivered; Sig...,Rule 4 — Insufficient evidence,True,True,True
17,D1018,owen_d,boutique_threads,Never received,escalate,low,Receipt evidence is contradicted or retracted ...,Reason: never received; Status: delivered; Sig...,Rule 4 — Conflicting evidence,False,True,True
18,D1019,liang_c,audio_attic,Arrived - does not power on,refund,high,The seller acknowledges the reported fault and...,Reason: arrived - does not power on; Status: d...,Seller-confirmed fault and refund,False,True,True
19,D1020,priya_s,stagegear_co,Wrong item shipped,refund,high,The seller acknowledges a listing or fulfillme...,Reason: wrong item shipped; Status: delivered;...,Rule 2 — Seller acknowledges error,True,True,True

Saved: reloop_decisions.csv

# Validate

In [49]:
# Inspect 5 disputes that need closer review

review_ids = ["D1003", "D1004", "D1006", "D1008", "D1010"]

review_cases = evidence[
    evidence["order_id"].isin(review_ids)
]

display(review_cases)

,order_id,buyer_handle,seller_handle,item,price_usd,dispute_reason,dispute_filed_date,carrier,signature_required,signed_by,delivery_status,last_scan_date,last_scan_location,delivered_date,delivery_notes,conversation
2,D1003,quick_flip99,north_collectibles,Signed Baseball,89,Never received,2025-01-08,SwiftShip,No,NaN,Delivered,2025-01-07,local depot,2025-01-07,left at door no signature,"[2025-01-08] Buyer: never got this, need a refund"
3,D1004,helen_ok,stagegear_co,Guitar Pedal,60,Damaged on arrival,2025-01-09,ParcelEx,No,NaN,Delivered,2025-01-08,local depot,2025-01-08,left at door,[2025-01-09] Buyer: pedal case arrived cracked...
5,D1006,priya_s,gearhead_supply,Bike Helmet,75,Not as described,2025-01-13,ParcelEx,No,NaN,Delivered,2025-01-11,local depot,2025-01-11,left at door,[2025-01-13] Seller: it was one small scuff on...
7,D1008,quick_flip99,audio_attic,Turntable,180,Never received,2025-01-19,SwiftShip,No,NaN,Delivered,2025-01-18,local depot,2025-01-18,left at door no signature,"[2025-01-19] Buyer: never received this, pleas..."
9,D1010,sam_k,gearhead_supply,Weight Plates,95,Never received,2025-01-21,ParcelEx,Yes,S.KAPOOR,Delivered,2025-01-19,NaN,2025-01-19,signed by recipient,"[2025-01-21] Buyer: I never got this, someone ..."

In [48]:
# D1004 aur D1006 ke complete conversations
for dispute_id in ["D1004", "D1006"]:
    print(f"\n{'='*50}")
    print(dispute_id)

    row = evidence[evidence["order_id"] == dispute_id].iloc[0]

    print("\nDispute reason:", row["dispute_reason"])
    print("\nTracking notes:", row["delivery_notes"])
    print("\nFull conversation:")
    print(row["conversation"])

==================================================
D1004

Dispute reason: Damaged on arrival

Tracking notes: left at door

Full conversation:
[2025-01-09] Buyer: pedal case arrived cracked, attaching a photo
[2025-01-09] Seller: so sorry - our listing says DOA damage is covered, refunding now

==================================================
D1006

Dispute reason: Not as described

Tracking notes: left at door

Full conversation:
[2025-01-13] Seller: it was one small scuff on the underside when I checked it before shipping, not sure what happened after that
[2025-01-13] Buyer: listing said "like new, tiny scuff" but this has multiple scratches, feels used

In [50]:
results["verdict"].value_counts(normalize=True).mul(100).round(1)

verdict
escalate    55.0
refund      30.0
deny        15.0
Name: proportion, dtype: float64

# Check the important cases

In [51]:
check_ids = ["D1004", "D1010", "D1011", "D1016", "D1019"]

results.loc[
    results["order_id"].isin(check_ids),
    ["order_id", "dispute_reason", "verdict",
     "confidence", "reason", "evidence", "rule_applied"]
]

,order_id,dispute_reason,verdict,confidence,reason,evidence,rule_applied
3,D1004,Damaged on arrival,refund,high,The seller confirms that the reported damage i...,so sorry - our listing says doa damage is cove...,Seller-confirmed damage coverage
9,D1010,Never received,deny,high,The non-receipt claim conflicts with credible ...,Signed delivery: True; buyer acknowledged rece...,Rule 3 — Confirmed delivery
10,D1011,Arrived broken,escalate,low,Evidence is insufficient for a confident decis...,Reason: arrived broken; Status: delivered; Not...,Rule 4 — Insufficient or conflicting evidence
15,D1016,Wrong color,deny,medium,The conversation indicates the parties already...,"Buyer: partial refund is fine, thanks got blue...",Rule 5 — Issue already resolved
18,D1019,Arrived - does not power on,escalate,low,Evidence is insufficient for a confident decis...,Reason: arrived - does not power on; Status: d...,Rule 4 — Insufficient or conflicting evidence

In [52]:
# three cases
check_ids = ["D1010", "D1011", "D1019"]

evidence.loc[
    evidence["order_id"].isin(check_ids),
    ["order_id", "dispute_reason", "conversation",
     "delivery_status", "signed_by", "delivery_notes"]
]

,order_id,dispute_reason,conversation,delivery_status,signed_by,delivery_notes
9,D1010,Never received,"[2025-01-21] Buyer: I never got this, someone ...",Delivered,S.KAPOOR,signed by recipient
10,D1011,Arrived broken,[2025-01-22] Seller: yeah that packaging was t...,Delivered,NaN,left at door
18,D1019,Arrived - does not power on,[2025-02-17] Buyer: amp doesn't turn on at all...,Delivered,L.C.,signed by recipient

In [53]:
# full conversion
for order_id in ["D1010", "D1011", "D1019"]:
    row = evidence.loc[evidence["order_id"] == order_id].iloc[0]

    print(f"\n{'='*20} {order_id} {'='*20}")
    print("Dispute:", row["dispute_reason"])
    print("Conversation:\n", row["conversation"])

==================== D1010 ====================
Dispute: Never received
Conversation:
 [2025-01-21] Buyer: I never got this, someone else must have signed for it
[2025-01-21] Seller: the tracking shows a signature at your address, I'm not sure what happened on your end

==================== D1011 ====================
Dispute: Arrived broken
Conversation:
 [2025-01-22] Seller: yeah that packaging was too thin, I've switched to rigid mailers since, refunding you
[2025-01-22] Buyer: record is snapped in half, photo attached, the package corner looks crushed too

==================== D1019 ====================
Dispute: Arrived - does not power on
Conversation:
 [2025-02-17] Buyer: amp doesn't turn on at all
[2025-02-17] Seller: try holding the power button for 5 sec, sometimes it needs a firmware reset
[2025-02-17] Buyer: tried that, still nothing
[2025-02-17] Seller: ok, that's a real fault then - refunding you

In [56]:
# Check the three cases we just reviewed
display(
    results.loc[
        results["order_id"].isin(["D1010", "D1011", "D1019"]),
        ["order_id", "verdict", "confidence", "reason", "rule_applied"]
    ]
)

,order_id,verdict,confidence,reason,rule_applied
9,D1010,escalate,medium,"Tracking records a signature, but the buyer di...",Rule 4 — Conflicting evidence
10,D1011,refund,high,The seller acknowledges the reported fault and...,Seller-confirmed fault and refund
18,D1019,refund,high,The seller acknowledges the reported fault and...,Seller-confirmed fault and refund

In [57]:
# Check that all 20 disputes received a decision
print("Total decisions:", len(results))
print("Missing verdicts:", results["verdict"].isna().sum())
print("Duplicate order IDs:", results["order_id"].duplicated().sum())

Total decisions: 20
Missing verdicts: 0
Duplicate order IDs: 0

# Final Summery

In [58]:
print("Total disputes:", len(results))
print("\nVerdict counts:")
print(results["verdict"].value_counts())

print("\nConfidence counts:")
print(results["confidence"].value_counts())

print("\nRule counts:")
print(results["rule_applied"].value_counts())

Total disputes: 20

Verdict counts:
verdict
escalate    11
refund       8
deny         1
Name: count, dtype: int64

Confidence counts:
confidence
low       10
high       8
medium     2
Name: count, dtype: int64

Rule counts:
rule_applied
Rule 4 — Insufficient evidence                   6
Rule 4 — Conflicting evidence                    3
Rule 2 — Seller acknowledges error               3
Rule 1 — Non-delivery                            2
Rule 4 — Insufficient or conflicting evidence    2
Seller-confirmed fault and refund                2
Seller-confirmed damage coverage                 1
Rule 5 — Issue already resolved                  1
Name: count, dtype: int64